### ISSUE TITLE
Decrypting with multiple recipients

### ISSUE THREAD

**Issue by cinnaboot** [quite/age-plugin-tkey#1]
Hi, thanks for this plugin.

I'm trying to use this with another age tool, [passage](https://github.com/FiloSottile/passage), but it seems to fail when decrypting a file that was encrypted for multiple recipients.

```
$ age -d -i tkey-identity test_data.age
age: error: tkey plugin: failed to read line: EOF
age: report unexpected or unhelpful errors at https://filippo.io/age/report
```
It works if I try it with the regular age key:
```
$ age -d -i age-identity test_data.age
somepassword
someusername
somewebsite

```

I tried debugging with [delve](https://github.com/go-delve/delve), and it seems to die here: https://github.com/FiloSottile/age/blob/main/cmd/age/age.go#L436

I assume the age program hands off to the plugin here, but I'm not a go developer, so don't know how to debug from here.

**Comment by quite** [comment]
Hey! Thanks for the report. Actually I have just recently run into this myself. I've spent some time refactoring everything (branch `rework` in all 3 repositories; this, tkeyx25519 and tkey-device-x25519), and actually tried out a few more use-cases... Hm, so it is actually something encrypted to multiple recipients that doesn't work. Since age-plugin-tkey recipients are same as native X25519, I guess that makes it not matter what the multiple recipients are then.

I haven't tried my hands with delve yet. Perhaps you can made the plugin sleep a little at the beginning, and then use `dlv attach` to attach to the running plugin by pid? (sleep just to make sure you can catch it, there are probably more clever ways). If you try your hand on it, I recommend using the `rework` branches. The branches are a bit messy, just wip-commits, but the code should be better structured and neater.

Note that the tkey-device-x25519 app binary has changed, so the identity is not the same, i.e. no decryption of things encrypted for previous identity. But I guess you may be familiar with this? Actually the app protocol, and as well the parameters stored in the identity have also changed. All has changed :) But we want to work towards a stable, reliable generally usable X25519 device app (and by extension, age plugin).

**Comment by quite** [comment]
I'll probably have less time to work on this in the coming weeks.

**Comment by quite** [comment]
I realised that this may have something to do with how we handle any error during decryption attempt. We need to think through if any error actually is fatal, and if some error needs to be communicated over the plugin protocol. And as well ensure that the protocol is followed even if we have some error.

**Comment by cinnaboot** [comment]
Getting to the point where I can actually use the debugger on the plugin has been a hurdle.

What's worked so far:
- `# echo 0 > /proc/sys/kernel/yama/ptrace_scope` to allow attaching the debugger
- compile the plugin with system go libs instead of the podman script (maybe some ABI differences?)
- add a sleep timer before the call to main.runIdentity() in main.run() `time.Sleep(20 * time.Second)`
- run age decrypt with a tkey identity, and attach the the new process `$ dlv attach $(pgrep age-plugin-tkey)`
- add a breakpoint for main.runIdentity(), and continue

Edit)
- also still can't inspect all the program variables because `Warning: debugging optimized function` :(

**Comment by cinnaboot** [comment]
Also, I made a makefile for testing, in case that's useful to someone: https://gist.github.com/cinnaboot/95c3dd5562875930974aa281477a55d3

The rework branch doesn't work for me. Decrypting always fails with `age: error: tkey plugin: failed to read line: EOF`. I made sure to use the matching age version too `filippo/plugin-8a01d201c863`. I'm using a hardware tkey though, so maybe it's different on QEMU?

**Comment by quite** [comment]
> The rework branch doesn't work for me. Decrypting always fails with `age: error: tkey plugin: failed to read line: EOF`. I made sure to use the matching age version too `filippo/plugin-8a01d201c863`.

Did you also remember to build tkey-device-x25519 from its rework branch? And copied it in place in this repo (see `make copy-deviceapp`). You can use `age-plugin-tkey --version` to see the hash of the embedded device app, for verification.

> I'm using a hardware tkey though, so maybe it's different on QEMU?

I'm using both and have not run into any discrepancies. Also the current rework branches work on hw.

**Comment by cinnaboot** [comment]
Ok, that did help. I can now decrypt with the rework branch.

I think I found a bug though. Previously, on the rework branch, I was using the podman script to build, and it looks like both the tkey-device-x25519, and the age-plugin-tkey are using the old checksums on the rework branches:
https://github.com/quite/tkey-device-x25519/blob/rework/x25519/app.bin.sha512
https://github.com/quite/age-plugin-tkey/blob/rework/internal/tkey/app.bin.sha512

I get: `c7588d01bb4dbcd83e2afb5c6e7ebb268bf9f29139cc59ff8c1d75979e458088f7f232f006391a20d67d8a1f56a9ecf49e625ca25b73f8e75d18b2246e778804  app.bin` for the latest device app.

Also, the podman [script](https://github.com/quite/age-plugin-tkey/blob/rework/contrib/build-in-container.sh) doesn't seem to check out the updated branch of the device app. Not sure if you're using that for testing.

**Comment by cinnaboot** [comment]
Oh, I also found a really dumb way to get around the optimized function thing in delve. Run the debugger, and copy the temporary binary, __debug_bin, to a backup file, and rename that to age-plugin-tkey.

Looks like delve adds a few hundred KB of info to the binary.

**Comment by quite** [comment]
Nice with some company working on this! I didn't expect... so yeah i didn't care about the checksums for examples. Fixed now. And the podman script is fixed.

I think I've fixed the decryption of multi-recipient! And also some other things. Still we need to be kinder if the tkey is not present when a tkey-identity is passed to age. Currently it just breaks i think. I've pushed a todo.

I forced-pushed to the rework branch, cleaning up the history.

**Comment by cinnaboot** [comment]
Oh wow, decrypting with multiple recipients totally works now, thanks!

I'm really just bumbling around in the source though. Maybe I'm useful for motivation :).

**Comment by quite** [comment]
@cinnaboot i just pushed a thing which should make age ask user to plug in tkey if it can't be found when the identity is looked up. (only for the specific case ErrNoDevice, for now). Would you try it?

**Comment by cinnaboot** [comment]
I'm getting
```
$ ./age/age  -d -i tkey-identity test_data.age
age: waiting on tkey plugin...
```

**Comment by cinnaboot** [comment]
Just to double-check my test set-up, I cleaned my ~/go/pkgs, and ~/.cache/go-build/*, and tried again with the same result.

If I go back to [4279f42b](https://github.com/quite/age-plugin-tkey/commit/4279f42b9a18c9d61f02a56626e47b8e4b0a8a4a), it still works. Updated [Makefile](https://gist.github.com/cinnaboot/95c3dd5562875930974aa281477a55d3)

**Comment by quite** [comment]
Ok, too bad. Good that you tested the previous commit, so it is only the last that's not working as it should then. I think I'll have to hold back with that feature for now then. If you want to try debugging you're welcome :) age is not supposed to hang, but it should display `Please plug in your TKey (press [1] for "OK" or [2] for "Cancel")` (the message you see about waiting on tkey plugin could be displayed, age does that if the plugin doesn't answer soon enough).

Also, I don't think you ever need to worry about cleaning go/pkgs or the go cache, I never had to.

In your Makefile there you're building age from that filippo/plugin branch. You don't really need to do that, but can use the latest release of age, 1.1.1. It's only age-plugin-tkey that needs to use that branch as dep, because it uses some newly exported stuff there.

**Comment by cinnaboot** [comment]
That's good to know about the age branch.

~~If I step into runIdentity() on that latest commit, it seems to get stuck in the main for loop waiting for `s.typ == "done"`.~~

~~If I dump the contents of the bufio.NewReader:~~
```
(dlv) p r
*bufio.Reader {
        buf: []uint8 len: 4096, cap: 4096, [45,62,32,97,100,100,45,105,100,101,110,116,105,116,121,32,65,71,69,45,80,76,85,71,73,78,45,84,75,69,89,45,49,70,52,52,75,84,56,56,52,69,82,74,88,48,89,48,85,74,90,68,50,65,84,48,55,51,69,69,51,86,67,83,...+4032 more],
        rd: io.Reader(*os.File) *{
                file: *(*os.file)(0xc00007a060),},
        r: 331,
        w: 340,
        err: error nil,
        lastByte: 10,
        lastRuneSize: -1,}
(dlv)
```
~~it looks like the 'lastByte' counter stops incrementing. Maybe waiting for a null byte? I'm not sure sure how to get the input to the reader in the debugger. `r := bufio.NewReader(os.Stdin)`~~

Oops, that wasn't the problem. I just didn't let it finish looping. It actually gets stuck somewhere in tryIdentities()

**Comment by cinnaboot** [comment]
Ok, it was here: `> main.tryIdentities() ./cmd/age-plugin-tkey/runidentity.go:148`
```
tryNext:
	for _, idBytes := range rawIdentities {
		for {
			id, err := identity.NewIdentityFromBytes(idBytes)
			if err != nil {
```
If I have the tkey plugged in, err is always nil, and the the id keeps getting repeatedly added to identities.

**Comment by quite** [comment]
Oh gosh, so perhaps a `break` after `identities = append(identities, id)` fixes it?

**Comment by quite** [comment]
I pushed the confirm stuff to `rework-confirm`

**Comment by cinnaboot** [comment]
> Oh gosh, so perhaps a `break` after `identities = append(identities, id)` fixes it?

Yeah, that works now. And I still get the confirmation dialog if I remove the tkey.

I didn't make any timings, but it seems significantly slower now though.

**Comment by cinnaboot** [comment]
Oh, that's probably because I left the 20 second sleep in there :P

**Comment by quite** [comment]
Yeah I really doesn't do anything more than before, this is all error handling basically. I've now added another message if the tkey is running the wrong device app, pushed to `rework-confirm`.

Just to confirm, you're only get the confirm message if tkey is not plugged in, right?

**Comment by cinnaboot** [comment]
That's correct.

**Comment by cinnaboot** [comment]
Also, it would be helpful when using delve to copy the device app out of the container when building: [patch](https://gist.github.com/cinnaboot/603937fc1a68a240ba8536936f2f54e8)

**Comment by quite** [comment]
Added! I've pushed all this stuff to `rework` branch now, as it seems to be working well enough.

**Comment by quite** [comment]
Added some more handling of wrong app running/wrong tkey/not touched.

**Comment by cinnaboot** [comment]
Looks like device app checksum was updated here https://github.com/quite/age-plugin-tkey/commit/f6161f34610b14e5d965e9c95e070f8436686cc8 , but the device app rework branch hasn't changed, so the checksum fails. Maybe local only changes?

**Comment by quite** [comment]
No that was me forgetting to push! done thx

**Comment by dylangerdaly** [comment]
> I'm trying to use this with another age tool, [passage](https://github.com/FiloSottile/passage)

You probably already know, but [gopass](https://github.com/gopasspw/gopass) also supports `age` as a backend

**Comment by quite** [comment]
I've cleaned up stuff and merged rework branches into main now. wip still but..

**Comment by quite** [comment]
Multiple recipients ought to work, right @cinnaboot ?

**Comment by quite** [comment]
For some reason, when ciphertext is encrypted to multiple identities and touch is required, the TKey has to be touched 2 times when decrypting using it. I wrote something about it in the new manual test here: https://github.com/quite/age-plugin-tkey/blob/main/tests/test2.sh#L50 -- but my thought there may be plain wrong, and there this might just be some issue with my plugin logic. Happy if anybody has time to dig into this, perhaps @cinnaboot @dylangerdaly @dehanj ? ;)

**Comment by quite** [comment]
OK this was bugging me too much, and I learned more about it. Documented in readme how multiple touches sometimes can be avoided: https://github.com/quite/age-plugin-tkey#multiple-recipients
